version: 2.1

parameters:
  run_by_api:
    type: boolean
    default: false

jobs:
  regular:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run: echo "I was run normally"
      - run: "curl --request POST \ --url https://circleci.com/api/v2/project/github/ryanbourdais/CircleCIKoansConfig15/pipeline \ --header 'authorization: Basic [4d08abc88549cbf740eabaee8e768225a370d44d]' \ --header 'content-type: application/json' \ "

  api-job:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run: echo "I was run by API"

workflows:
  normal:
    jobs:
      - regular

  api-workflow:
    when: << pipeline.parameters.run_by_api >> # Without modifying the config, run api-job
    jobs:
      - api-job

# 4d08abc88549cbf740eabaee8e768225a370d44d