version: 2.1

parameters:
  run_by_api:
    type: boolean
    default: false

jobs:
  regular:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run: echo "I was run normally"
      
  api-job:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run: echo "I was run by API"

workflows:
  normal:
    jobs:
      - regular

  api-workflow:
    when: << pipeline.parameters.run_by_api >> # Without modifying the config, run api-job
    jobs:
      - api-job

# admin key: 4d08abc88549cbf740eabaee8e768225a370d44d  base64: ODVjN2I4ODJhZmRiMTRhMzNkZDZjMWQ3MjFlNGEyMjgzODk3ZGE3Nw==
# read key:  1f31d562afed6004c2738d06a50f716f71591dbc  base64: MWYzMWQ1NjJhZmVkNjAwNGMyNzM4ZDA2YTUwZjcxNmY3MTU5MWRiYw==